openapi: 3.0.0
info:
  title: "Flinder"
  description: "Definición de la entidad User"
  version: 1.0.0

servers:
  - url: "http://localhost:4200"
    description: "Development server"
tags:
  - name: Usuarios
  - name: Usuario único
security:
  - BasicAuth: []

paths:
  "/users":
    get:
      tags:
        - Usuarios
      summary: "Return all Users"
      parameters:
        - in: query
          name: gender
          description: Género del usuario
          schema:
            type: string
        - in: query
          name: username
          description: Alias del usuario
          schema:
            type: string
        - in: query
          name: firstname
          description: Nombre real del usuario
          schema:
            type: string
        - in: query
          name: lastname
          description: Apellido del usuario
          schema:
            type: string
        - in: query
          name: email
          description: Correo del usuario
          schema:
            type: string
        - in: query
          name: age
          description: Edad del usuario
          schema:
            type: number
        - in: query
          name: postalcode
          description: Código postal del usuario
          schema:
            type: number
        - in: query
          name: city
          description: Ciudad del usuario
          schema:
            type: string
        - in: query
          name: country
          description: País del usuario
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: "All Media in Common"
                items: 
                  $ref: "#/components/schemas/User"
        "204":
          description: "No content"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
        - Usuarios
      summary: "Insert a new User"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                gender:
                  type: string
                  enum: [Male, Female, Other]
                  example: Male
                username:
                  type: string
                  example: PepitoPerez
                firstname:
                  type: string
                  example: Pepito
                lastname:
                  type: string
                  example: Pérez
                email:
                  type: string
                  example: pepito@perez.com
                birthday:
                  type: string
                  format: date-time
                city:
                  type: string
                  example: Madrid
                country:
                  type: string
                  example: España
                phone:
                  type: string
                  example: +3476576576876
                address:
                  type: string
                  example: C/ Lombarda
              required:
                - lastname
                - firtname
                - username
                - email
                - birthday
                - gender
                - city
                - country
      responses:
        "201":
          $ref: "#/components/responses/Ok"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/ServerError"
  "/users/{userID}":
    get:
      tags: 
        -  Usuario único
      summary: "Returns all infoarmation of the selected User"
      parameters:
        - $ref: "#/components/parameters/userId"
      responses:
        "200":
          description: Ok
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfo"
        "404": 
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
    patch:
      tags:
        - Usuario único
      summary: "Updates the User entity"
      parameters:
        - $ref: "#/components/parameters/userId"
      requestBody:
        description: User data to patch
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInfo"
      responses:
        "200":
          $ref: "#/components/responses/Ok"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
    delete:
      tags:
        - Usuario único
      summary: "Delete the selected User"
      parameters:
        - $ref: "#/components/parameters/userId"
      responses:
        "204":
          $ref: "#/components/responses/Deleted"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
  "/users/{userID}/matches":
    get:
      tags:
        - Usuario único
      summary: "Returns User's Matches"
      parameters:
        - $ref: "#/components/parameters/userId"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserMatches"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/ServerError"
  "/users/{userID}/favourites":
    get:
      tags:
        - Usuario único
      summary: "Returns User's Favourites"
      parameters:
        - $ref: "#/components/parameters/userId"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Favourites"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/ServerError"
  "/users/{userID}/series":
    get:
      tags:
        - Usuario único 
      summary: "Returns User's Series"
      parameters:
        - $ref: "#/components/parameters/userId"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Series"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
  "/users/{userID}/lists":
    get:
      tags:
        - Usuario único
      summary: "Returns User's Lists"
      parameters:
        - $ref: "#/components/parameters/userId"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Lists"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
  "/users/{userID}/chats":
    get:
      tags:
        - Usuario único
      summary: "Returns User's Chats"
      parameters:
        - $ref: "#/components/parameters/userId"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chats"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
  "/users/{userID}/movies":
    get:
      tags:
        - Usuario único
      summary: "Returns User's Movies"
      parameters:
        - $ref: "#/components/parameters/userId"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Movies"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  responses:
    Ok:
      description: "Ok"
    Deleted:
      description: "Deleted"
    BadRequest:
      description: "Bad Request"
    ServerError:
      description: "Internal server error"
    NotFound:
      description: "Requested resource not found"
  parameters:
    userId:
      in: path
      name: userID
      description: "The user ID"
      required: true
      schema:
        type: number
        minimum: 1
  schemas:
    User:
      properties:
        ID:
          type: number
          description: "User Identifier"
        Info:
          description: "All information related to the selected list"
          properties:
            UserName:
              type: string
              description: "User nick name"
              example: "Javi"
            FirstName:
              type: string
              description: "User name"
              example: "Javi"
            LastName:
              type: string
              description: "User Surname"
              example: "Muruzábal"
            Email:
              type: string
              description: "User email"
              example: "javimuruzabal@hotmail.com"
            Birthday:
              type: string
              description: "User birthday"
              example: "14-06-2000"
            PostalCode:
              type: number
              description: "User ZIP Code Residency"
              example: "31500"
            City:
              type: number
              description: "User City"
              example: "Pamplona"
            Country:
              type: number
              description: "User Country"
              example: "Spain"
            Address:
              type: number
              description: "User Address"
              example: "Mayor Street"
            Gender:
              type: string
              description: "User Gender"
              example: "Male"
              enum: [Male, Female, Other]
            Phone:
              type: number
              description: "User Phone"
              example: "666666666"
            Image:
              type: number
              description: "User Profile Image"
              example: "profile.png"
          required:
            - ID
        Auth:
          description: "Fields for User's Auth"
          properties:
            Token:
              type: string
              description: "Token generated when the User Signs In"
              example: "vouwebfvwpiergboutcaiusc734t23j4ltbgo"
            RefreshToken:
              type: number
              description: "Number of hours to refresh the Token"
              example: 24
            Password:
              type: string
              description: "Password defined by User to Sign In"
              example: "*****"
        LastLogin:
          type: string
          format: date-time
          description: "Timestamp of User's Last Connection"
          example: 16534935935
        CreationDate:
          type: number
          description: "Timestamp of User's Sign Up"
          example: 16534935935
        UpdateDate:
          type: number
          description: "Timestamp of User's profile update"
          example: 16534932235
        MatchesCriteria:
          description: "Matches Criteria"
          properties:
            Age:
              type: number
              description: "Age Of Match User"
              example: 30
            Gender:
              type: string
              description: "Gender Of Match User"
              example: "Female"
            Distance:
              type: number
              description: "Distance on Km of Match User"
              example: 3
            Favourites:
              type: array
              items:
                type: number
                description: "All Media in Common"
                example: "[id, id, id...]"
        LastGeo:
          description: "Last Geo"
          properties:
            Latitude:
              type: number
              example: -104.53
            Longitude:
              type: number
              example: 99.04
        Favourites:
          type: array
          items:
            type: number
            example: "[id, id, ...]"
            description: "User Favourites"
        Series:
          type: array
          items:
            type: number
            example: "[id, id, ...]"
            description: "User Series"
        Lists:
          type: array
          items:
            type: number
            example: "[id, id, ...]"
            description: "User Lists"
        Chats:
          type: array
          items:
            type: number
            example: "[id, id, ...]"
            description: "User Chats"
        Matches:
          type: array
          items:
            type: number
            example: "[id, id, ...]"
            description: "User Matches"
        Movies:
          type: array
          items:
            type: number
            example: "[id, id, ...]"
            description: "User Movies"
      required:
        - ID
    UserInfo:
      description: "All information related to the selected user"
      properties:
        username:
          type: string
          description: "User nick name"
          example: "JaviMuru"
        firstname:
          type: string
          description: "User name"
          example: "Javi"
        lastname:
          type: string
          description: "User Surname"
          example: "Muruzábal"
        email:
          type: string
          description: "User email"
          example: "javimuruzabal@hotmail.com"
        birthday:
          type: string
          description: "User birthday"
          example: "14-06-2000"
        postalcode:
          type: number
          description: "User ZIP Code Residency"
          example: "31500"
        city:
          type: number
          description: "User City"
          example: "Pamplona"
        country:
          type: number
          description: "User Country"
          example: "Spain"
        address:
          type: number
          description: "User Address"
          example: "Mayor Street"
        gender:
          type: number
          description: "User Gender"
          example: "Male"
        phone:
          type: number
          description: "User Phone"
          example: "666666666"
        image:
          type: number
          description: "User Profile Image"
          example: "profile.png"
    UserAuth:
      description: "All information related User Auth"
      properties:
        Token:
          type: string
          description: "Token generated when the User Signs In"
          example: "vouwebfvwpiergboutcaiusc734t23j4ltbgo"
        RefreshToken:
          type: number
          description: "Number of hours to refresh the Token"
          example: 24
        Password:
          type: string
          description: "Password defined by User to Sign In"
          example: "*****"
    UserMatches:
      description: "All information related User Matches"
      type: array
      items:
        type: object
        properties:
          Age:
            type: number
            description: "Age Of Match User"
            example: 30
          Gender:
            type: string
            description: "Gender Of Match User"
            example: "Female"
          Distance:
            type: number
            description: "Distance on Km of Match User"
            example: 3
          Favourites:
            type: array
            items:
              type: number
              description: "All Media in Common"
              example: "[mediaId, mediaId, mediaId, ...]"
    UserGeo:
      description: "All information related User LastGeo"
      type: object
      properties:
        Latitude:
          type: number
          example: -104.53
        Longitude:
          type: number
          example: 99.04
    Favourites:
      description: "User Favourites"
      type: array
      items:
        type: string
        example: "[mediaId, mediaId, mediaId, ...]"
        description: "All user's favourites"
    Series:
      description: "User Series"
      type: array
      items:
        type: string
        example: "[serieId, serieId, serieId, ...]"
        description: "All user's series"
    Lists:
      description: "User Lists"
      type: array
      items:
        type: string
        example: "[listId, listId, listId, ...]"
        description: "All user lists"
    Chats:
      description: "User Chats"
      type: array
      items:
        type: string
        example: "[chatId, chatId, chatId, ...]"
        description: "All user's chats"
    Matches:
      description: "User Chats"
      type: array
      items:
        type: string
        example: "[matchId, matchId, matchId, ...]"
        description: "All user matches"
    Movies:
      description: "User Movies"
      type: array
      items:
        type: string
        example: "[movieId, movieId, movieId, ...]"
        description: "All user's movies"
